const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');

// Extended: https://swagger.io/specification/#infoObject
const options = {
    swaggerDefinition: {
        info: {
            title: 'User Api',
            description: 'Test API with autogenerated swagger doc',
        },
        host: ['http://localhost:3000'],
        schemes: ['htpp']

    },
    // [routes/*.js]
    apis: ['endpoints.js'],
};

const specs = swaggerJsdoc(options);

module.exports = (app) => {
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
}