const swaggerJsdoc = require('swagger-jsdoc');
const swaggerUi = require('swagger-ui-express');


const options = {
    swaggerDefinition: {
        info: {
            title: 'Test API',
            verison: '1.0.0',
            description: 'Test Express API with autogenerated Swagger',

        },
        basePath: '/',
    },
    apis: ['endpoints.js'],
};

const specs = swaggerJsdoc(options);

module.exports = (app) => {
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
}